name: tweet

on:
  push:
env:
  API_KEY: ${{ secrets.API_KEY }}
  API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "ths is env=${{ env.env_1 }}"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: curl -sSL https://install.python-poetry.org | python -
      - run: export PATH="$PATH:$HOME/.poetry/bin"
      - uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry config virtualenvs.in-project true && poetry install
      - run: poetry run python src/tweet.py
